# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"4\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\" \n\rOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8f\x01\n\x0eProductService\x12=\n\nPlaceOrder\x12\x16.products.OrderRequest\x1a\x17.products.OrderResponse\x12>\n\x0bUpdateOrder\x12\x16.products.OrderRequest\x1a\x17.products.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=28
  _globals['_ORDERREQUEST']._serialized_end=80
  _globals['_ORDERRESPONSE']._serialized_start=82
  _globals['_ORDERRESPONSE']._serialized_end=114
  _globals['_PRODUCTSERVICE']._serialized_start=117
  _globals['_PRODUCTSERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
